### PR TITLE
timetable italics + instituteCode search + theme preview background color

### PR DESCRIPTION
**Pull request by sleddev**
Fixed:
- Fullscreen timetable bug: https://discord.com/channels/1111649116020285532/1155750296610414705
- search schools based on instituteCode: https://discord.com/channels/1111649116020285532/1147934715341439007
- background color not updating in theme preview: https://discord.com/channels/1111649116020285532/1153619667848548452

### CODE REVIEW

**Comment by kimaah** [comment]
tested?

**Comment by sleddev** [comment]
yes

**Comment by PearooXD** [comment]
discord?

**Comment by sleddev** [comment]
mar van contributor rangom, amugy huskydev

**Comment by PearooXD** [comment]
o

**Pull request merged**
